#!/bin/bash

# Railway Deployment Script for RoboVibe Turbo Template

echo "🚂 Railway Deployment Setup"
echo "=========================="
echo ""

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "❌ Railway CLI not found. Please install it first:"
    echo "   brew install railway"
    echo "   or"
    echo "   curl -fsSL https://railway.app/install.sh | sh"
    exit 1
fi

echo "✅ Railway CLI is installed"
echo ""

# Instructions for manual setup
echo "📋 Manual Setup Instructions:"
echo ""
echo "1. First, login to Railway:"
echo "   railway login"
echo ""
echo "2. Create a new project:"
echo "   railway init --name robovibe-turbo"
echo ""
echo "3. Create PostgreSQL service:"
echo "   railway add"
echo "   Select: PostgreSQL"
echo ""
echo "4. Create API service:"
echo "   railway service create api"
echo ""
echo "5. Configure API service:"
echo "   railway link api"
echo "   railway variables set NODE_ENV=production"
echo "   railway variables set PORT=\${{PORT}}"
echo "   railway variables set DATABASE_URL=\${{POSTGRES_URL}}"
echo "   railway variables set CLERK_SECRET_KEY=<your-clerk-secret>"
echo "   railway variables set CLERK_WEBHOOK_SECRET=<your-webhook-secret>"
echo "   railway variables set CLIENT_URL=<web-service-url>"
echo "   railway variables set SERVER_URL=\${{RAILWAY_PUBLIC_DOMAIN}}"
echo "   railway variables set API_URL=\${{RAILWAY_PUBLIC_DOMAIN}}"
echo "   railway variables set OPENAI_API_KEY=<your-openai-key>"
echo "   railway variables set JWT_SECRET=<generate-secure-secret>"
echo ""
echo "6. Configure API build settings:"
echo "   Build Command: pnpm install --frozen-lockfile && pnpm build --filter=@repo/api..."
echo "   Start Command: cd apps/api && pnpm start"
echo "   Root Directory: /"
echo ""
echo "7. Create Web service:"
echo "   railway service create web"
echo ""
echo "8. Configure Web service:"
echo "   railway link web"
echo "   railway variables set VITE_API_URL=<api-service-url>"
echo "   railway variables set VITE_CLERK_PUBLISHABLE_KEY=<your-publishable-key>"
echo ""
echo "9. Configure Web build settings:"
echo "   Build Command: pnpm install --frozen-lockfile && pnpm build --filter=@repo/web..."
echo "   Start Command: cd apps/web && pnpm preview --port \$PORT --host 0.0.0.0"
echo "   Root Directory: /"
echo ""
echo "10. Deploy both services:"
echo "    railway up"
echo ""
echo "11. Run database migrations:"
echo "    railway run pnpm db:push"
echo ""
echo "🎉 Your application should now be deployed on Railway!"
echo ""
echo "📝 Note: Replace all <placeholders> with your actual values"
echo "📝 Note: Use railway domain command to get service URLs after deployment"